# Generated by Django 6.0.4 on 2026-04-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hortifruti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('unidad', models.CharField(default='kg', max_length=20, verbose_name='Unidad (kg, unid, etc.)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (R$)')),
                ('fecha_oferta', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('es_vegetal', models.BooleanField(default=False, verbose_name='¿Es Vegetal?')),
                ('activo', models.BooleanField(default=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Actual')),
            ],
            options={
                'verbose_name': 'Hortifruti',
                'verbose_name_plural': 'Hortifrutis',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Llegada de camión)'), ('SALIDA', 'Salida (Venta/Calculadora)'), ('PERDIDA', 'Pérdida (Fruta dañada/Merma)')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, help_text='Ej: Cliente compró en caja, o se pudrió por calor', null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tienda.hortifruti')),
            ],
        ),
    ]
