# Generated by Django 6.0.4 on 2026-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='anulado',
            field=models.BooleanField(default=False, verbose_name='¿Movimiento Anulado?'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
