# Generated by Django 6.0.4 on 2026-05-03 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_movimientoinventario_anulado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hortifruti',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='hortifruti',
            name='stock_actual',
        ),
        migrations.AlterField(
            model_name='hortifruti',
            name='unidad',
            field=models.CharField(default='kg', max_length=20, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='anulado',
            field=models.BooleanField(default=False, verbose_name='¿Anulado?'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Llegada de camión)'), ('SALIDA', 'Salida (Venta/Balanza)'), ('PERDIDA', 'Pérdida (Merma)')], max_length=10),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sede')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tienda.sucursal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockPorSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='tienda.hortifruti')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='tienda.sucursal')),
            ],
            options={
                'verbose_name': 'Stock por Sucursal',
                'verbose_name_plural': 'Stocks por Sucursales',
                'unique_together': {('sucursal', 'producto')},
            },
        ),
    ]
