# Generated by Django 6.0.4 on 2026-05-05 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_hortifruti_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='stockporsucursal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='tienda.sucursal'),
        ),
    ]
