# Generated by Django 6.0.4 on 2026-05-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_credencialhuella'),
    ]

    operations = [
        migrations.AddField(
            model_name='hortifruti',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Costo (R$)'),
        ),
        migrations.AlterField(
            model_name='hortifruti',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta (R$)'),
        ),
    ]
